# Základní nastavení
owner: allinwebservice
repo: status

# Weby, které chceš sledovat
sites:
  - name: Apliso
    url: https://apliso.net
  - name: ČSUZ
    url: https://csuz.cz
  - name: CNSC
    url: https://cnsc.cz
  - name: Infosafe
    url: https://infosafe.tech
  - name: Infosafe
    url: https://nope.allinweb.cz

# Status web (veřejná stránka)
status-website:
  # cname: status.allinweb.cz   # pokud chceš vlastní doménu, odkomentuj a nastav DNS
  baseUrl: /status              # pro github.io/status
  logoUrl: https://allinweb.cz/logo.png
  name: All In Web Service - Status
  introTitle: "Status Page for All In Web Service"
  introMessage: |
    Tato stránka zobrazuje dostupnost a historii monitoringu našich projektů.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/allinwebservice/status

# Komu automaticky přiřadit incidenty (kvůli e-mailům z GitHubu)
assignees:
  - allinwebservice
